In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [8]:
np.linspace(0, 7, 11)

array([0. , 0.7, 1.4, 2.1, 2.8, 3.5, 4.2, 4.9, 5.6, 6.3, 7. ])

In [9]:
np.zeros([5, 2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [11]:
n[0,1]

np.int64(2)

In [12]:
n[0, 1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [13]:
n[:, 1]

array([20,  5,  8])

In [14]:
np.random.rand(5, 2)

array([[0.5324763 , 0.32455708],
       [0.17120236, 0.10220163],
       [0.66795849, 0.25289748],
       [0.17647739, 0.91242436],
       [0.67903158, 0.24485588]])

In [15]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [17]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [21]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [23]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [24]:
a + 1

array([1, 2, 3, 4, 5])

In [25]:
a >= 2

array([False, False,  True,  True,  True])

In [27]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [32]:
a

array([0, 1, 2, 3, 4])

In [33]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [28]:
a > b

array([False, False,  True,  True,  True])

In [29]:
a[a > b]

array([2, 3, 4])

In [34]:
a.min()
a.max()
a.sum()

np.int64(10)